"""Inicialización de migraciones

Revision ID: 21805d67bb5b
Revises: 
Create Date: 2024-06-26 14:26:40.257665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21805d67bb5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_image', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('blog_image')

    # ### end Alembic commands ###
